import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import voidPlugin from "./packages/config/eslint-plugin-void/index.mjs";

export default [
  {
    // The design-system tree is read-only reference the product rebuilds FROM.
    // Its harness files load React and Babel from a CDN by design; linting them
    // would report defects in something that never ships.
    ignores: [
      "design-system/**",
      "apps/*/public/theme/**",
      "packages/tokens/dist/**",
      "node_modules/**",
      // Any Next output directory, however distDir is configured.
      "**/.next*/**",
      // Generated by `next build`; its triple-slash references are Next's own.
      "apps/*/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,jsx,ts,tsx}"],
    plugins: { react, void: voidPlugin },
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: { react: { version: "detect" } },
    rules: {
      "void/no-style-literals": "error",
      "void/no-next-font": "error",
      // A leading underscore marks a parameter kept deliberately — usually to
      // hold a signature stable while the implementation behind it is pending.
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  {
    // The gates and the generator are build tooling, not component code: they
    // legitimately handle raw values because measuring them is their job, and
    // they run in Node rather than the browser.
    files: ["scripts/**", "packages/tokens/src/**", "packages/config/**", "*.config.mjs", "apps/*/next.config.mjs", "apps/*/postcss.config.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        URL: "readonly",
        __dirname: "readonly",
      },
    },
    rules: { "void/no-style-literals": "off" },
  },
  {
    // Browser code inside the rendered gate runs in the page, not in Node.
    files: ["scripts/gates/theme-swap.render.mjs"],
    languageOptions: {
      globals: { document: "readonly", getComputedStyle: "readonly", window: "readonly" },
    },
  },
];
